Modified yaml file

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -169,7 +169,21 @@ jobs:
             --command-id "$COMMAND_ID" \
             --instance-id "${{ secrets.EC2_INSTANCE_ID }}"
 
+          STATUS=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ secrets.EC2_INSTANCE_ID }}" \
+            --query "Status" \
+            --output text)
+
+          echo "SSM Command Status: $STATUS"
+
+          if [ "$STATUS" != "Success" ]; then
+            echo "Deployment or health check failed."
+            exit 1
+          fi
+
           echo "Deployment and health check succeeded."
+          
   # Verify the deployment by checking the health endpoint of the Flask application
   Verify-Deployment:
     needs: Deploy-to-EC2
